Nuklear function override
camchenry/shaderview pull request #4
Opened 2017-07-22 01:52 UTC by Nuthen

2017-07-24 23:14 UTC, camchenry requested changes

2017-07-24 23:14 UTC, camchenry commented on states/splash.lua
> +
I would prefer to see this go away and instead check that the callbacks exists in the first place before calling them.

2017-07-24 23:14 UTC, camchenry commented on main.lua
> +    local leftoutCallbacks = {'keypressed', 'keyreleased', 'mousepressed', 'mousereleased', 'mousemoved', 'textinput', 'wheelmoved'}
Really minor nitpick: I'm using underscores in this project (sort of an experiment) so it should be something like left_out_callbacks

2017-07-24 23:14 UTC, camchenry commented on main.lua
> +    State.current():keypressed(key, code, isRepeat)
I think it will be more maintainable in the future to just check if the current state has the callback in the first place.

2017-07-26 02:14 UTC, Nuthen commented
I have made relevant changes.

2017-11-18 02:39 UTC, camchenry commented
I'm not using Nuklear anymore, as you know, so I'm going to close this because it's no longer relevant.

2017-11-18 02:39 UTC, closed without merging